#lang racket

(require rackunit
         rackunit/text-ui
         redex/reduction-semantics
         racket/runtime-path
         (prefix-in sl: "s/language.rkt")
         (prefix-in ss: "s/source.rkt")
         (prefix-in swf: "s/wf.rkt")
         (prefix-in el: "e/language.rkt")
         (prefix-in es: "e/source.rkt")
         (prefix-in ewf: "e/wf.rkt")
         (prefix-in nl: "n/language.rkt")
         (prefix-in ns: "n/source.rkt")
         (prefix-in nwf: "n/wf.rkt")
         "vertical.rkt")

(provide DISJUNCTION-ORACLE-TESTS)

(define sigma-empty/s
  '(state () () () (label "state")))

(define (sigma/e support)
  `(state (Support ,@support) () () () (label "state")))

(define (sigma/n next)
  `(state ,next () () () (label "state")))

(define owners-empty '(Owners))
(define owners-u0 '(Owners (Owner (u:0) (label "u0"))))
(define owners-u1 '(Owners (Owner (u:1) (label "u1"))))
(define owners-u2 '(Owners (Owner (u:2) (label "u2"))))
(define owners-u3 '(Owners (Owner (u:3) (label "u3"))))
(define owners-u4 '(Owners (Owner (u:4) (label "u4"))))
(define owners-u0-u1
  '(Owners
    (Owner (u:0) (label "u0"))
    (Owner (u:1) (label "u1"))))
(define owners-u0-u2
  '(Owners
    (Owner (u:0) (label "u0"))
    (Owner (u:2) (label "u2"))))
(define owners-u1-u2
  '(Owners
    (Owner (u:1) (label "u1"))
    (Owner (u:2) (label "u2"))))
(define owners-u1-u3
  '(Owners
    (Owner (u:1) (label "u1"))
    (Owner (u:3) (label "u3"))))

(define expected-rule-names
  '(allocate-fresh
    commit-choice-answer
    conj-fail
    conj-return
    disequality-fail
    disequality-success
    expand-conjunction
    expand-disjunction
    fail
    finish-failure
    finish-success
    reassociate-left-result
    resume-left-choice-success
    skip-left-failure
    succeed
    unify-fail
    unify-success
    unify-violates-disequality))

(define (rule-names relation)
  (map (lambda (name) (string->symbol (~a name)))
       (reduction-relation->rule-names relation)))

(define (wf-proofs/s frontier)
  (build-derivations
   (swf:wf-disjunction-oracle/s? ,frontier)))

(define (wf-proofs/e frontier)
  (build-derivations
   (ewf:wf-disjunction-oracle/e? ,frontier)))

(define (wf-proofs/n frontier)
  (build-derivations
   (nwf:wf-disjunction-oracle/n? ,frontier)))

(define (trace-final source trace)
  (match trace
    ['() source]
    [_ (second (last trace))]))

;; Five literal one-step rows.  E and N are written independently rather than
;; generated by Q; the vertical maps are tested against these declarations.
(define expand-source/s
  `(More
    (Work
     ,owners-u0
     ((succeed (label "left"))
      ∨
      (succeed (label "right"))
      (label "choice"))
     ,sigma-empty/s)))
(define expand-target/s
  `(More
    (DisjL
     ,owners-u0
     (Work ,owners-empty (succeed (label "left")) ,sigma-empty/s)
     (Work ,owners-empty (succeed (label "right")) ,sigma-empty/s))))
(define expand-source/e
  `(More
    (Work
     ((succeed (label "left"))
      ∨
      (succeed (label "right"))
      (label "choice"))
     ,(sigma/e '(u:0)))))
(define expand-target/e
  `(More
    (DisjL
     (Work (succeed (label "left")) ,(sigma/e '(u:0)))
     (Work (succeed (label "right")) ,(sigma/e '(u:0))))))
(define expand-source/n
  `(More
    (Work
     ((succeed (label "left"))
      ∨
      (succeed (label "right"))
      (label "choice"))
     ,(sigma/n 1))))
(define expand-target/n
  `(More
    (DisjL
     (Work (succeed (label "left")) ,(sigma/n 1))
     (Work (succeed (label "right")) ,(sigma/n 1)))))

(define skip-source/s
  `(More
    (DisjL
     ,owners-u0
     (Dead ,owners-u1)
     (Work ,owners-u2 (succeed (label "survivor")) ,sigma-empty/s))))
(define skip-target/s
  `(More
    (Work ,owners-u0-u2 (succeed (label "survivor")) ,sigma-empty/s)))
(define skip-source/e
  `(More
    (DisjL
     (Dead (Support u:0 u:1))
     (Work (succeed (label "survivor")) ,(sigma/e '(u:0 u:2))))))
(define skip-target/e
  `(More
    (Work (succeed (label "survivor")) ,(sigma/e '(u:0 u:2)))))
(define skip-source/n
  `(More
    (DisjL
     (Dead 2)
     (Work (succeed (label "survivor")) ,(sigma/n 2)))))
(define skip-target/n
  `(More (Work (succeed (label "survivor")) ,(sigma/n 2))))

(define reassociate-source/s
  `(More
    (DisjL
     ,owners-u0
     (DisjL
      ,owners-u1
      (Returned ,owners-u2 ,sigma-empty/s)
      (Work ,owners-u3 (succeed (label "middle")) ,sigma-empty/s))
     (Work ,owners-u4 (succeed (label "right")) ,sigma-empty/s))))
(define reassociate-target/s
  `(More
    (DisjL
     ,owners-u0
     (Returned ,owners-u1-u2 ,sigma-empty/s)
     (DisjL
      ,owners-empty
      (Work ,owners-u1-u3 (succeed (label "middle")) ,sigma-empty/s)
      (Work ,owners-u4 (succeed (label "right")) ,sigma-empty/s)))))
(define reassociate-source/e
  `(More
    (DisjL
     (DisjL
      (Returned ,(sigma/e '(u:0 u:1 u:2)))
      (Work (succeed (label "middle")) ,(sigma/e '(u:0 u:1 u:3))))
     (Work (succeed (label "right")) ,(sigma/e '(u:0 u:4))))))
(define reassociate-target/e
  `(More
    (DisjL
     (Returned ,(sigma/e '(u:0 u:1 u:2)))
     (DisjL
      (Work (succeed (label "middle")) ,(sigma/e '(u:0 u:1 u:3)))
      (Work (succeed (label "right")) ,(sigma/e '(u:0 u:4)))))))
(define reassociate-source/n
  `(More
    (DisjL
     (DisjL
      (Returned ,(sigma/n 3))
      (Work (succeed (label "middle")) ,(sigma/n 3)))
     (Work (succeed (label "right")) ,(sigma/n 2)))))
(define reassociate-target/n
  `(More
    (DisjL
     (Returned ,(sigma/n 3))
     (DisjL
      (Work (succeed (label "middle")) ,(sigma/n 3))
      (Work (succeed (label "right")) ,(sigma/n 2))))))

(define commit-source/s
  `(More
    (DisjL
     ,owners-u0
     (Returned ,owners-u1 ,sigma-empty/s)
     (Work ,owners-u2 (succeed (label "residual")) ,sigma-empty/s))))
(define commit-target/s
  `(Emit
    ,owners-u0
    (Answer ,owners-u1 ,sigma-empty/s)
    (More
     (Work ,owners-u2 (succeed (label "residual")) ,sigma-empty/s))))
(define commit-source/e
  `(More
    (DisjL
     (Returned ,(sigma/e '(u:0 u:1)))
     (Work (succeed (label "residual")) ,(sigma/e '(u:0 u:2))))))
(define commit-target/e
  `(Emit
    (Answer ,(sigma/e '(u:0 u:1)))
    (More
     (Work (succeed (label "residual")) ,(sigma/e '(u:0 u:2))))))
(define commit-source/n
  `(More
    (DisjL
     (Returned ,(sigma/n 2))
     (Work (succeed (label "residual")) ,(sigma/n 2)))))
(define commit-target/n
  `(Emit
    (Answer ,(sigma/n 2))
    (More (Work (succeed (label "residual")) ,(sigma/n 2)))))

(define resume-source/s
  `(More
    (Conj
     ,owners-u0
     (DisjL
      ,owners-u1
      (Returned ,owners-u2 ,sigma-empty/s)
      (Work ,owners-u3 (succeed (label "saved")) ,sigma-empty/s))
     (succeed (label "continuation")))))
(define resume-target/s
  `(More
    (DisjL
     ,owners-u0-u1
     (Work ,owners-u2 (succeed (label "continuation")) ,sigma-empty/s)
     (Conj
      ,owners-empty
      (Work ,owners-u3 (succeed (label "saved")) ,sigma-empty/s)
      (succeed (label "continuation"))))))
(define resume-source/e
  `(More
    (Conj
     (DisjL
      (Returned ,(sigma/e '(u:0 u:1 u:2)))
      (Work (succeed (label "saved")) ,(sigma/e '(u:0 u:1 u:3))))
     (succeed (label "continuation")))))
(define resume-target/e
  `(More
    (DisjL
     (Work (succeed (label "continuation"))
           ,(sigma/e '(u:0 u:1 u:2)))
     (Conj
      (Work (succeed (label "saved")) ,(sigma/e '(u:0 u:1 u:3)))
      (succeed (label "continuation"))))))
(define resume-source/n
  `(More
    (Conj
     (DisjL
      (Returned ,(sigma/n 3))
      (Work (succeed (label "saved")) ,(sigma/n 3)))
     (succeed (label "continuation")))))
(define resume-target/n
  `(More
    (DisjL
     (Work (succeed (label "continuation")) ,(sigma/n 3))
     (Conj
      (Work (succeed (label "saved")) ,(sigma/n 3))
      (succeed (label "continuation"))))))

(define direct-rows
  (list
   (list 'expand-disjunction
         expand-source/s expand-target/s
         expand-source/e expand-target/e
         expand-source/n expand-target/n)
   (list 'skip-left-failure
         skip-source/s skip-target/s
         skip-source/e skip-target/e
         skip-source/n skip-target/n)
   (list 'reassociate-left-result
         reassociate-source/s reassociate-target/s
         reassociate-source/e reassociate-target/e
         reassociate-source/n reassociate-target/n)
   (list 'commit-choice-answer
         commit-source/s commit-target/s
         commit-source/e commit-target/e
         commit-source/n commit-target/n)
   (list 'resume-left-choice-success
         resume-source/s resume-target/s
         resume-source/e resume-target/e
         resume-source/n resume-target/n)))

;; The active branch may reuse u:1 even when the incomparable sibling already
;; owns u:1.  The settled-answer case establishes the same fact across Emit.
(define sibling-allocation-source/s
  `(More
    (DisjL
     ,owners-u0
     (Work
      ,owners-empty
      (∃ (x:left)
         (succeed (label "left"))
         (label "left-fresh"))
      ,sigma-empty/s)
     (Work ,owners-u1 (succeed (label "right")) ,sigma-empty/s))))
(define sibling-allocation-target/s
  `(More
    (DisjL
     ,owners-u0
     (Work
      (Owners (Owner (u:1) (label "left-fresh")))
      (succeed (label "left"))
      ,sigma-empty/s)
     (Work ,owners-u1 (succeed (label "right")) ,sigma-empty/s))))

(define settled-allocation-source/s
  `(Emit
    ,owners-u0
    (Answer ,owners-u1 ,sigma-empty/s)
    (More
     (Work
      ,owners-empty
      (∃ (x:residual)
         (succeed (label "residual"))
         (label "residual-fresh"))
      ,sigma-empty/s))))
(define settled-allocation-target/s
  `(Emit
    ,owners-u0
    (Answer ,owners-u1 ,sigma-empty/s)
    (More
     (Work
      (Owners (Owner (u:1) (label "residual-fresh")))
      (succeed (label "residual"))
      ,sigma-empty/s))))

;; One finite witness simultaneously establishes: the outer fresh is shared
;; by both branches, each sibling allocates u:1/level 1 independently, and the
;; raw named trace preserves both answers without deduplication.
(define shared-reuse-source/s
  `(More
    (Work
     ,owners-empty
     (∃ (x:outer)
        ((∃ (x:left)
            (x:outer =? x:outer (label "left-shared"))
            (label "left-fresh"))
         ∨
         (∃ (x:right)
            (x:outer =? x:outer (label "right-shared"))
            (label "right-fresh"))
         (label "choice"))
        (label "outer"))
     ,sigma-empty/s)))

(define shared-reuse-source/e
  `(More
    (Work
     (∃ (x:outer)
        ((∃ (x:left)
            (x:outer =? x:outer (label "left-shared"))
            (label "left-fresh"))
         ∨
         (∃ (x:right)
            (x:outer =? x:outer (label "right-shared"))
            (label "right-fresh"))
         (label "choice"))
        (label "outer"))
     ,(sigma/e '()))))

(define shared-reuse-source/n
  `(More
    (Work
     (∃ (x:outer)
        ((∃ (x:left)
            (x:outer =? x:outer (label "left-shared"))
            (label "left-fresh"))
         ∨
         (∃ (x:right)
            (x:outer =? x:outer (label "right-shared"))
            (label "right-fresh"))
         (label "choice"))
        (label "outer"))
     ,(sigma/n 0))))

(define expected-shared-reuse-names
  '(allocate-fresh
    expand-disjunction
    allocate-fresh
    unify-success
    commit-choice-answer
    allocate-fresh
    unify-success
    finish-success))

(define shared-left-state/s
  '(state
    ()
    ()
    ((u:0 =? u:0 (label "left-shared")))
    (label "state")))
(define shared-right-state/s
  '(state
    ()
    ()
    ((u:0 =? u:0 (label "right-shared")))
    (label "state")))
(define shared-left-state/e
  '(state
    (Support u:0 u:1)
    ()
    ()
    ((u:0 =? u:0 (label "left-shared")))
    (label "state")))
(define shared-right-state/e
  '(state
    (Support u:0 u:1)
    ()
    ()
    ((u:0 =? u:0 (label "right-shared")))
    (label "state")))
(define shared-left-state/n
  '(state
    2
    ()
    ()
    ((0 =? 0 (label "left-shared")))
    (label "state")))
(define shared-right-state/n
  '(state
    2
    ()
    ()
    ((0 =? 0 (label "right-shared")))
    (label "state")))

(define expected-shared-reuse-final/s
  `(Emit
    (Owners (Owner (u:0) (label "outer")))
    (Answer
     (Owners (Owner (u:1) (label "left-fresh")))
     ,shared-left-state/s)
    (Last
     (Owners (Owner (u:1) (label "right-fresh")))
     (Answer ,owners-empty ,shared-right-state/s))))
(define expected-shared-reuse-final/e
  `(Emit
    (Answer ,shared-left-state/e)
    (Last (Answer ,shared-right-state/e))))
(define expected-shared-reuse-final/n
  `(Emit
    (Answer ,shared-left-state/n)
    (Last (Answer ,shared-right-state/n))))

(define-runtime-path s-language-path "s/language.rkt")
(define-runtime-path s-source-path "s/source.rkt")
(define-runtime-path s-wf-path "s/wf.rkt")
(define-runtime-path e-language-path "e/language.rkt")
(define-runtime-path e-source-path "e/source.rkt")
(define-runtime-path e-wf-path "e/wf.rkt")
(define-runtime-path n-language-path "n/language.rkt")
(define-runtime-path n-source-path "n/source.rkt")
(define-runtime-path n-wf-path "n/wf.rkt")
(define-runtime-path vertical-path "vertical.rkt")
(define-runtime-path shared-path "private/shared.rkt")

(define DISJUNCTION-ORACLE-TESTS
  (test-suite
   "independent Disjunction source/WF oracle"

   (test-case
    "S/E/N grammars state the left-active and emitted carriers"
    (check-true
     (redex-match?
      sl:disjunction-s-oracle-lang
      g
      '((succeed (label "l"))
        ∨
        (fail (label "r"))
        (label "or"))))
    (check-true
     (redex-match?
      sl:disjunction-s-oracle-lang
      W
      '(DisjL (Owners) (Dead (Owners)) (Dead (Owners)))))
    (check-true
     (redex-match?
      sl:disjunction-s-oracle-lang
      F
      '(Emit
        (Owners)
        (Answer (Owners) (state () () () (label "state")))
        (Done (Owners)))))
    (check-true
     (redex-match?
      el:disjunction-e-oracle-lang
      W
      '(DisjL (Dead (Support)) (Dead (Support)))))
    (check-true
     (redex-match?
      el:disjunction-e-oracle-lang
      F
      '(Emit
        (Answer (state (Support) () () () (label "state")))
        (Done (Support)))))
    (check-true
     (redex-match?
      nl:disjunction-n-oracle-lang
      W
      '(DisjL (Dead 0) (Dead 0))))
    (check-true
     (redex-match?
      nl:disjunction-n-oracle-lang
      F
      '(Emit
        (Answer (state 0 () () () (label "state")))
        (Done 0))))
    (check-true
     (redex-match?
      sl:disjunction-s-oracle-lang
      WorkPath
      (term (DisjL (Owners) hole (Dead (Owners))))))
    (check-true
     (redex-match?
      el:disjunction-e-oracle-lang
      SpineContext
      (term
       (Emit
        (Answer (state (Support) () () () (label "state")))
        hole))))
    (check-true
     (redex-match?
      nl:disjunction-n-oracle-lang
      SpineContext
      (term
       (Emit
        (Answer (state 0 () () () (label "state")))
        hole))))
    ;; No right-active rail or adjacent feature constructor is admitted.
    (for ([excluded
           (in-list
            '((suspend (succeed (label "body")) (label "delay"))
              (relcall r (x:a) (label "call"))))])
      (check-false (redex-match? sl:disjunction-s-oracle-lang g excluded))
      (check-false (redex-match? el:disjunction-e-oracle-lang g excluded))
      (check-false (redex-match? nl:disjunction-n-oracle-lang g excluded)))
    (check-false
     (redex-match?
      sl:disjunction-s-oracle-lang
      W
      '(DisjR (Owners) (Dead (Owners)) (Dead (Owners)))))
    (check-false
     (redex-match?
      el:disjunction-e-oracle-lang
      W
      '(DisjL (Support) (Dead (Support)) (Dead (Support)))))
    (check-false
     (redex-match?
      nl:disjunction-n-oracle-lang
      F
      '(Emit 0 (Answer (state 0 () () () (label "state"))) (Done 0)))))

   (test-case
    "each relation has 13 core and exactly five Disjunction labels"
    (for ([actual
           (in-list
            (list (rule-names ss:disjunction-s-oracle-red)
                  (rule-names es:disjunction-e-oracle-red)
                  (rule-names ns:disjunction-n-oracle-red)))])
      (check-equal? (length actual) 18)
      (check-equal? (length actual)
                    (length (remove-duplicates actual)))
      (check-equal? (sort actual symbol<?) expected-rule-names)))

   (test-case
    "five independently written S/E/N equations have exact raw targets"
    (for ([row (in-list direct-rows)])
      (match-define
        (list label
              source/s target/s
              source/e target/e
              source/n target/n)
        row)
      (define expected/s (list (list label target/s)))
      (define expected/e (list (list label target/e)))
      (define expected/n (list (list label target/n)))
      (check-equal?
       (ss:raw-successors/disjunction/s source/s)
       expected/s
       (~a label " S"))
      (check-equal?
       (es:raw-successors/disjunction/e source/e)
       expected/e
       (~a label " E"))
      (check-equal?
       (ns:raw-successors/disjunction/n source/n)
       expected/n
       (~a label " N"))
      ;; Literal rows also pin all three direct vertical equations.
      (check-equal? (Q-SE/F/disjunction source/s) source/e)
      (check-equal? (Q-SE/F/disjunction target/s) target/e)
      (check-equal? (Q-EN/F/disjunction source/e) source/n)
      (check-equal? (Q-EN/F/disjunction target/e) target/n)
      (check-equal? (Q-SN/F/disjunction source/s) source/n)
      (check-equal? (Q-SN/F/disjunction target/s) target/n)))

   (test-case
    "lexical substitution crosses both branches and respects shadowing"
    (define shadowed-goal
      '((∃ (x:outer)
           ((x:outer =? x:free (label "left"))
            ∨
            (x:free != x:outer (label "nested"))
            (label "inner-choice"))
           (label "shadow"))
        ∨
        (x:free =? x:other (label "right"))
        (label "outer-choice")))
    (define expected-s
      '((∃ (x:outer)
           ((x:outer =? u:8 (label "left"))
            ∨
            (u:8 != x:outer (label "nested"))
            (label "inner-choice"))
           (label "shadow"))
        ∨
        (u:8 =? u:9 (label "right"))
        (label "outer-choice")))
    (define expected-n
      '((∃ (x:outer)
           ((x:outer =? 8 (label "left"))
            ∨
            (8 != x:outer (label "nested"))
            (label "inner-choice"))
           (label "shadow"))
        ∨
        (8 =? 9 (label "right"))
        (label "outer-choice")))
    (check-equal?
     (ss:subst-goal/disjunction/s
      shadowed-goal
      '((x:outer u:7) (x:free u:8) (x:other u:9)))
     expected-s)
    (check-equal?
     (es:subst-goal/disjunction/e
      shadowed-goal
      '((x:outer u:7) (x:free u:8) (x:other u:9)))
     expected-s)
    (check-equal?
     (term
      (ns:subst-goal/disjunction/n
       ,shadowed-goal
       ((x:outer 7) (x:free 8) (x:other 9))))
     expected-n))

   (test-case
    "WF has one raw proof for every direct source and target"
    (for ([row (in-list direct-rows)])
      (match-define
        (list label
              source/s target/s
              source/e target/e
              source/n target/n)
        row)
      ;; Exact lengths are proof-multiplicity checks; nothing is deduplicated.
      (for ([proofs
             (in-list
              (list (wf-proofs/s source/s)
                    (wf-proofs/s target/s)
                    (wf-proofs/e source/e)
                    (wf-proofs/e target/e)
                    (wf-proofs/n source/n)
                    (wf-proofs/n target/n)))])
        (check-equal? (length proofs) 1 (~a label)))))

   (test-case
    "WF recurses through both branches and emitted answer/residual"
    (define ill-scoped/s
      `(Emit
        ,owners-empty
        (Answer ,owners-empty ,sigma-empty/s)
        (More
         (DisjL
          ,owners-u0
          (Work ,owners-empty (succeed (label "left")) ,sigma-empty/s)
          (Work
           ,owners-empty
           (u:9 =? (nat 0) (label "unbound"))
           ,sigma-empty/s)))))
    (define ill-scoped/e
      `(Emit
        (Answer ,(sigma/e '()))
        (More
         (DisjL
          (Work (succeed (label "left")) ,(sigma/e '(u:0)))
          (Work
           (u:9 =? (nat 0) (label "unbound"))
           ,(sigma/e '(u:0)))))))
    (define ill-scoped/n
      `(Emit
        (Answer ,(sigma/n 0))
        (More
         (DisjL
          (Work (succeed (label "left")) ,(sigma/n 1))
          (Work
           (1 =? (nat 0) (label "unbound"))
           ,(sigma/n 1))))))
    (check-equal? (wf-proofs/s ill-scoped/s) '())
    (check-equal? (wf-proofs/e ill-scoped/e) '())
    (check-equal? (wf-proofs/n ill-scoped/n) '()))

   (test-case
    "direct vertical squares preserve raw names and multiplicities"
    (for ([row (in-list direct-rows)])
      (match-define
        (list label source/s _target/s source/e _target/e _source/n _target/n)
        row)
      (check-true (Q-SE-step-square/raw?/disjunction source/s) (~a label))
      (check-true (Q-EN-step-square/raw?/disjunction source/e) (~a label))
      (check-true (Q-SN-step-square/raw?/disjunction source/s) (~a label))
      (check-true (Q-SN-composition?/disjunction source/s) (~a label))
      (for ([sides
             (in-list
              (list (Q-SE-step-square-sides/disjunction source/s)
                    (Q-EN-step-square-sides/disjunction source/e)
                    (Q-SN-step-square-sides/disjunction source/s)))])
        (check-equal? (map length sides) '(1 1) (~a label))))

    ;; Allocation is inherited but its feature-aware substitution and active
    ;; path view are essential new extension seams.
    (for ([source/s
           (in-list
            (list sibling-allocation-source/s
                  settled-allocation-source/s))]
          [target/s
           (in-list
            (list sibling-allocation-target/s
                  settled-allocation-target/s))])
      (check-equal?
       (ss:raw-successors/disjunction/s source/s)
       (list (list 'allocate-fresh target/s)))
      (define source/e (Q-SE/F/disjunction source/s))
      (check-true (Q-SE-step-square/raw?/disjunction source/s))
      (check-true (Q-EN-step-square/raw?/disjunction source/e))
      (check-true (Q-SN-step-square/raw?/disjunction source/s))
      (check-true (Q-SN-composition?/disjunction source/s))
      (for ([sides
             (in-list
              (list (Q-SE-step-square-sides/disjunction source/s)
                    (Q-EN-step-square-sides/disjunction source/e)
                    (Q-SN-step-square-sides/disjunction source/s)))])
        (check-equal? (map length sides) '(1 1)))))

   (test-case
    "bounded shared-outer trace reuses one sibling-local allocation"
    (define trace/s
      (ss:trace/disjunction/s shared-reuse-source/s 16))
    (define trace/e
      (es:trace/disjunction/e shared-reuse-source/e 16))
    (define trace/n
      (ns:trace/disjunction/n shared-reuse-source/n 16))
    (check-equal? (Q-SE/F/disjunction shared-reuse-source/s)
                  shared-reuse-source/e)
    (check-equal? (Q-EN/F/disjunction shared-reuse-source/e)
                  shared-reuse-source/n)
    (check-equal? (Q-SN/F/disjunction shared-reuse-source/s)
                  shared-reuse-source/n)
    (check-equal? (map first trace/s) expected-shared-reuse-names)
    (check-equal? (map first trace/e) expected-shared-reuse-names)
    (check-equal? (map first trace/n) expected-shared-reuse-names)
    (check-equal? (length trace/s) 8)
    (check-equal? (length trace/e) 8)
    (check-equal? (length trace/n) 8)
    (check-equal? (trace-final shared-reuse-source/s trace/s)
                  expected-shared-reuse-final/s)
    (check-equal? (trace-final shared-reuse-source/e trace/e)
                  expected-shared-reuse-final/e)
    (check-equal? (trace-final shared-reuse-source/n trace/n)
                  expected-shared-reuse-final/n)
    (for ([step/s (in-list trace/s)]
          [step/e (in-list trace/e)]
          [step/n (in-list trace/n)])
      (match-define (list name/s target/s) step/s)
      (match-define (list name/e target/e) step/e)
      (match-define (list name/n target/n) step/n)
      (check-equal? name/s name/e)
      (check-equal? name/s name/n)
      (check-equal? (Q-SE/F/disjunction target/s) target/e)
      (check-equal? (Q-EN/F/disjunction target/e) target/n)
      (check-equal? (Q-SN/F/disjunction target/s) target/n)
      ;; One proof per row and one raw successor per nonterminal trace state.
      (check-equal? (length (wf-proofs/s target/s)) 1)
      (check-equal? (length (wf-proofs/e target/e)) 1)
      (check-equal? (length (wf-proofs/n target/n)) 1)))

   (test-case
    "oracle declarations import no framework, generated, or production layer"
    (for ([path
           (in-list
            (list s-language-path
                  s-source-path
                  s-wf-path
                  e-language-path
                  e-source-path
                  e-wf-path
                  n-language-path
                  n-source-path
                  n-wf-path
                  vertical-path
                  shared-path))])
      (define contents (file->string path))
      (check-false (regexp-match? #rx"framework/" contents))
      (check-false (regexp-match? #rx"generated/" contents))
      (check-false (regexp-match? #rx"src/search-lattice" contents))
      (check-false (regexp-match? #rx"stage-generators" contents))))))

(module+ test
  (run-tests DISJUNCTION-ORACLE-TESTS))

(module+ main
  (define failures (run-tests DISJUNCTION-ORACLE-TESTS))
  (unless (zero? failures)
    (error 'disjunction-oracle-tests "~a test failure(s)" failures)))
