#lang racket

(require redex/reduction-semantics)

(provide define-pk-compression-spec)

;; This is the compositional presentation of compression. It is deliberately
;; generated by a different schema from the direct symbolic equations.
(define-syntax-rule
  (define-pk-compression-spec
    compression-spec-lang
    compressed-lang
    machine-refocus-query/direct
    machine-step/direct
    wf-frontier/K
    compressed-step/direct
    initial-compressed/direct
    decode-BM
    replay-labels/exact
    replay-span/exact
    replay-spans/exact
    root-fresh-machine
    not-root-fresh-machine
    corridor-continue-first
    corridor-stop-first
    corridor-continue-second
    corridor-stop-second
    compressed-step/spec
    compression-step-square
    compression-steps-square
    reachable-compression-correspondence)
  (begin
    (define-extended-language compression-spec-lang
      compressed-lang
      ;; Every kernel edge is a producer: its success/failure result must be
      ;; consumed by one following control edge.  The exact kell is retained.
      [ProducerFollowup kell
                        (suspend-goal delay)]
      [AfterUnfinished
       (allocate-fresh core)
       (expand-conjunction core)
       (expand-disjunction disj)
       (conj-return core)
       (late-distribute-settled disj)
       (late-distribute-right-settled search-join)]
      [OtherFirst
       (expose-frontier-fresh core)
       (finish-success core)
       (finish-failure core)
       (force-delay delay)
       (commit-choice-answer disj)
       (commit-right-choice-answer search-join)
       (expose-choice-through-work-fresh disj)
       (expose-choice-through-work-fresh search-join)
       (erase-dead-fresh core)
       (bubble-delay-through-fresh delay)
       (conj-fail core)
       (bubble-delay-through-conj delay)
       (skip-left-failure disj)
       (rail-enter-right search-join)
       (reassociate-left-result disj)
       (skip-right-failure search-join)
       (rail-return-left search-join)
       (reassociate-right-result search-join)]
      [NotAfter ProducerFollowup OtherFirst])

    (define-judgment-form
      compression-spec-lang
      #:contract (decode-BM B M)
      #:mode (decode-BM I O)

      [(machine-refocus-query/direct (MQWork NW WF) M)
       ---------------------------------------------------- "decode running residual"
       (decode-BM (BRun NW WF) M)]

      [(machine-refocus-query/direct (MQWork SR WF) M)
       ---------------------------------------------------- "decode settled residual"
       (decode-BM (BSettled SR WF) M)]

      [(machine-refocus-query/direct (MQWork Dead WF) M)
       ---------------------------------------------------- "decode dead residual"
       (decode-BM (BDead WF) M)]

      [(machine-refocus-query/direct (MQWork (PendingDelay W) WF) M)
       ---------------------------------------------------- "decode delayed residual"
       (decode-BM (BDelay W WF) M)]

      [---------------------------------------------------- "decode final residual"
       (decode-BM (BFinal T FF) (MFrontier T FF))])

    (define-judgment-form
      compression-spec-lang
      #:contract (replay-labels/exact M MLabels M)
      #:mode (replay-labels/exact I I O)

      [---------------------------------------------------- "replay no exact labels"
       (replay-labels/exact M () M)]

      [(machine-step/direct M_0 ell M_1)
       (replay-labels/exact M_1 (ell_rest (... ...)) M_2)
       ---------------------------------------------------- "replay one exact label"
       (replay-labels/exact M_0 (ell ell_rest (... ...)) M_2)])

    (define-judgment-form
      compression-spec-lang
      #:contract (replay-span/exact M Span M)
      #:mode (replay-span/exact I I O)

      [(replay-labels/exact M_0 (ell_0 ell_rest (... ...)) M_1)
       ---------------------------------------------------- "replay nonempty span"
       (replay-span/exact
        M_0
        (transition-span ell_0 ell_rest (... ...))
        M_1)])

    (define-judgment-form
      compression-spec-lang
      #:contract (replay-spans/exact M Spans M)
      #:mode (replay-spans/exact I I O)

      [---------------------------------------------------- "replay no spans"
       (replay-spans/exact M () M)]

      [(replay-span/exact M_0 Span M_1)
       (replay-spans/exact M_1 (Span_rest (... ...)) M_2)
       ---------------------------------------------------- "replay one span"
       (replay-spans/exact M_0 (Span Span_rest (... ...)) M_2)])

    (define-judgment-form
      compression-spec-lang
      #:contract (root-fresh-machine M)
      #:mode (root-fresh-machine I)

      [---------------------------------------------------- "root WorkFresh machine state"
       (root-fresh-machine
        (MWork (WorkFresh intro W tag) BF))])

    (define-judgment-form
      compression-spec-lang
      #:contract (not-root-fresh-machine M)
      #:mode (not-root-fresh-machine I)

      [---------------------------------------------------- "nonfresh root machine state"
       (not-root-fresh-machine (MWork NF BF))]

      [---------------------------------------------------- "machine state below ordinary frame"
       (not-root-fresh-machine (MWork W LF))]

      [---------------------------------------------------- "frontier machine state is not root fresh"
       (not-root-fresh-machine (MFrontier T FF))])

    (define-judgment-form
      compression-spec-lang
      #:contract (corridor-continue-first ell M)
      #:mode (corridor-continue-first I I)

      [---------------------------------------------------- "producer requires followup"
       (corridor-continue-first ProducerFollowup M)]

      [(root-fresh-machine M)
       ---------------------------------------------------- "unfinished result exposes root fresh"
       (corridor-continue-first AfterUnfinished M)])

    (define-judgment-form
      compression-spec-lang
      #:contract (corridor-stop-first ell M)
      #:mode (corridor-stop-first I I)

      [---------------------------------------------------- "ordinary first edge stops"
       (corridor-stop-first OtherFirst M)]

      [(not-root-fresh-machine M)
       ---------------------------------------------------- "unfinished result has no root exposure"
       (corridor-stop-first AfterUnfinished M)])

    (define-judgment-form
      compression-spec-lang
      #:contract (corridor-continue-second ell M)
      #:mode (corridor-continue-second I I)

      [(root-fresh-machine M)
       ---------------------------------------------------- "second edge exposes root fresh"
       (corridor-continue-second AfterUnfinished M)])

    (define-judgment-form
      compression-spec-lang
      #:contract (corridor-stop-second ell M)
      #:mode (corridor-stop-second I I)

      [---------------------------------------------------- "non-producing second edge stops"
       (corridor-stop-second NotAfter M)]

      [(not-root-fresh-machine M)
       ---------------------------------------------------- "second unfinished result has no exposure"
       (corridor-stop-second AfterUnfinished M)])

    (define-judgment-form
      compression-spec-lang
      #:contract (compressed-step/spec B Span M)
      #:mode (compressed-step/spec I O O)

      [(decode-BM B_0 M_0)
       (machine-step/direct M_0 ell_1 M_1)
       (corridor-continue-first ell_1 M_1)
       (machine-step/direct M_1 ell_2 M_2)
       (corridor-continue-second ell_2 M_2)
       (machine-step/direct M_2 ell_3 M_3)
       ---------------------------------------------------- "canonical three-edge corridor"
       (compressed-step/spec
        B_0
        (transition-span ell_1 ell_2 ell_3)
        M_3)]

      [(decode-BM B_0 M_0)
       (machine-step/direct M_0 ell_1 M_1)
       (corridor-continue-first ell_1 M_1)
       (machine-step/direct M_1 ell_2 M_2)
       (corridor-stop-second ell_2 M_2)
       ---------------------------------------------------- "canonical two-edge corridor"
       (compressed-step/spec
        B_0
        (transition-span ell_1 ell_2)
        M_2)]

      [(decode-BM B_0 M_0)
       (machine-step/direct M_0 ell_1 M_1)
       (corridor-stop-first ell_1 M_1)
       ---------------------------------------------------- "canonical one-edge corridor"
       (compressed-step/spec
        B_0
        (transition-span ell_1)
        M_1)])

    (define-judgment-form
      compression-spec-lang
      #:contract (compression-step-square B Span B M M)
      #:mode (compression-step-square I O O O O)

      [(decode-BM B_0 M_0)
       (compressed-step/direct B_0 Span B_1)
       (decode-BM B_1 M_1)
       (compressed-step/spec B_0 Span M_1)
       (replay-span/exact M_0 Span M_1)
       ---------------------------------------------------- "compressed/exact commuting square"
       (compression-step-square B_0 Span B_1 M_0 M_1)])

    (define-judgment-form
      compression-spec-lang
      #:contract (compression-steps-square B Spans B M M)
      #:mode (compression-steps-square I O O O O)

      [(decode-BM B M)
       ---------------------------------------------------- "empty compressed/exact path square"
       (compression-steps-square B () B M M)]

      [(compression-step-square B_0 Span B_1 M_0 M_1)
       (compression-steps-square
        B_1
        (Span_rest (... ...))
        B_2
        M_1
        M_2)
       ---------------------------------------------------- "nonempty compressed/exact path square"
       (compression-steps-square
        B_0
        (Span Span_rest (... ...))
        B_2
        M_0
        M_2)])

    (define-judgment-form
      compression-spec-lang
      #:contract (reachable-compression-correspondence F Spans B M)
      #:mode (reachable-compression-correspondence I O O O)

      [(wf-frontier/K F)
       (initial-compressed/direct F B_0)
       (compression-steps-square B_0 Spans B_1 M_0 M_1)
       ---------------------------------------------------- "reachable compressed/exact image"
       (reachable-compression-correspondence F Spans B_1 M_1)])))
