#lang racket

(require rackunit
         rackunit/text-ui
         redex/reduction-semantics
         racket/runtime-path
         "private/shared.rkt"
         (prefix-in sl: "s/language.rkt")
         (prefix-in ss: "s/source.rkt")
         (prefix-in swf: "s/wf.rkt")
         (prefix-in el: "e/language.rkt")
         (prefix-in es: "e/source.rkt")
         (prefix-in ewf: "e/wf.rkt")
         (prefix-in nl: "n/language.rkt")
         (prefix-in ns: "n/source.rkt")
         (prefix-in nwf: "n/wf.rkt")
         "vertical.rkt")

(provide SEARCH-ORACLE-TESTS)

(define OWNERS-EMPTY '(Owners))
(define SIGMA/S '(state () () () (label "search-state")))
(define SIGMA/E '(state (Support) () () () (label "search-state")))
(define SIGMA/N '(state 0 () () () (label "search-state")))
(define SUCCEED-GOAL '(succeed (label "mixed-success")))
(define FAIL-GOAL '(fail (label "mixed-failure")))
(define RIGHT-GOAL '(succeed (label "mixed-right")))

(define OWNERS-U0 '(Owners (Owner (u:0) (label "u0"))))
(define OWNERS-U1 '(Owners (Owner (u:1) (label "u1"))))
(define OWNERS-U2 '(Owners (Owner (u:2) (label "u2"))))
(define OWNERS-U3 '(Owners (Owner (u:3) (label "u3"))))
(define OWNERS-U4 '(Owners (Owner (u:4) (label "u4"))))

(define (sigma/e support)
  `(state (Support ,@support) () () () (label "search-state")))

(define (sigma/n next)
  `(state ,next () () () (label "search-state")))

(struct mixed-case (name label source target) #:transparent)

;; These are literal Search terms, not imported corpus data and not generated by
;; a vertical map.  Together they exercise every inherited feature rule in a
;; context supplied by the other feature.
(define MIXED-CASES/S
  (list
   (mixed-case
    'suspend-under-emit
    'suspend-goal
    `(Emit
      ,OWNERS-EMPTY
      (Answer ,OWNERS-EMPTY ,SIGMA/S)
      (More
       (Work
        ,OWNERS-EMPTY
        (suspend ,SUCCEED-GOAL (label "suspend-under-emit"))
        ,SIGMA/S)))
    `(Emit
      ,OWNERS-EMPTY
      (Answer ,OWNERS-EMPTY ,SIGMA/S)
      (More
       (PendingDelay
        ,OWNERS-EMPTY
        (Work ,OWNERS-EMPTY ,SUCCEED-GOAL ,SIGMA/S)))))

   (mixed-case
    'bubble-choice-payload
    'bubble-delay-through-conj
    `(More
      (Conj
       ,OWNERS-EMPTY
       (PendingDelay
        ,OWNERS-EMPTY
        (DisjL
         ,OWNERS-EMPTY
         (Work ,OWNERS-EMPTY ,SUCCEED-GOAL ,SIGMA/S)
         (Dead ,OWNERS-EMPTY)))
       ,RIGHT-GOAL))
    `(More
      (PendingDelay
       ,OWNERS-EMPTY
       (Conj
        ,OWNERS-EMPTY
        (DisjL
         ,OWNERS-EMPTY
         (Work ,OWNERS-EMPTY ,SUCCEED-GOAL ,SIGMA/S)
         (Dead ,OWNERS-EMPTY))
        ,RIGHT-GOAL))))

   (mixed-case
    'force-under-emit
    'force-delay
    `(Emit
      ,OWNERS-EMPTY
      (Answer ,OWNERS-EMPTY ,SIGMA/S)
      (More
       (PendingDelay
        ,OWNERS-EMPTY
        (DisjL
         ,OWNERS-EMPTY
         (Work ,OWNERS-EMPTY ,SUCCEED-GOAL ,SIGMA/S)
         (Dead ,OWNERS-EMPTY)))))
    `(Emit
      ,OWNERS-EMPTY
      (Answer ,OWNERS-EMPTY ,SIGMA/S)
      (Forced
       ,OWNERS-EMPTY
       (More
        (DisjL
         ,OWNERS-EMPTY
         (Work ,OWNERS-EMPTY ,SUCCEED-GOAL ,SIGMA/S)
         (Dead ,OWNERS-EMPTY))))))

   (mixed-case
    'expand-under-forced
    'expand-disjunction
    `(Forced
      ,OWNERS-EMPTY
      (More
       (Work
        ,OWNERS-EMPTY
        (,FAIL-GOAL ∨ ,SUCCEED-GOAL (label "choice-under-forced"))
        ,SIGMA/S)))
    `(Forced
      ,OWNERS-EMPTY
      (More
       (DisjL
        ,OWNERS-EMPTY
        (Work ,OWNERS-EMPTY ,FAIL-GOAL ,SIGMA/S)
        (Work ,OWNERS-EMPTY ,SUCCEED-GOAL ,SIGMA/S)))))

   (mixed-case
    'skip-to-pending
    'skip-left-failure
    `(More
      (DisjL
       ,OWNERS-EMPTY
       (Dead ,OWNERS-EMPTY)
       (PendingDelay
        ,OWNERS-EMPTY
        (Work ,OWNERS-EMPTY ,SUCCEED-GOAL ,SIGMA/S))))
    `(More
      (PendingDelay
       ,OWNERS-EMPTY
       (Work ,OWNERS-EMPTY ,SUCCEED-GOAL ,SIGMA/S))))

   (mixed-case
    'reassociate-pending-residual
    'reassociate-left-result
    `(More
      (DisjL
       ,OWNERS-EMPTY
       (DisjL
        ,OWNERS-EMPTY
        (Returned ,OWNERS-EMPTY ,SIGMA/S)
        (PendingDelay
         ,OWNERS-EMPTY
         (Work ,OWNERS-EMPTY ,SUCCEED-GOAL ,SIGMA/S)))
       (Dead ,OWNERS-EMPTY)))
    `(More
      (DisjL
       ,OWNERS-EMPTY
       (Returned ,OWNERS-EMPTY ,SIGMA/S)
       (DisjL
        ,OWNERS-EMPTY
        (PendingDelay
         ,OWNERS-EMPTY
         (Work ,OWNERS-EMPTY ,SUCCEED-GOAL ,SIGMA/S))
        (Dead ,OWNERS-EMPTY)))))

   (mixed-case
    'commit-under-forced
    'commit-choice-answer
    `(Forced
      ,OWNERS-EMPTY
      (More
       (DisjL
        ,OWNERS-EMPTY
        (Returned ,OWNERS-EMPTY ,SIGMA/S)
        (PendingDelay
         ,OWNERS-EMPTY
         (Work ,OWNERS-EMPTY ,SUCCEED-GOAL ,SIGMA/S)))))
    `(Forced
      ,OWNERS-EMPTY
      (Emit
       ,OWNERS-EMPTY
       (Answer ,OWNERS-EMPTY ,SIGMA/S)
       (More
        (PendingDelay
         ,OWNERS-EMPTY
         (Work ,OWNERS-EMPTY ,SUCCEED-GOAL ,SIGMA/S))))))

   (mixed-case
    'resume-with-delayed-residual
    'resume-left-choice-success
    `(Forced
      ,OWNERS-EMPTY
      (More
       (Conj
        ,OWNERS-EMPTY
        (DisjL
         ,OWNERS-EMPTY
         (Returned ,OWNERS-EMPTY ,SIGMA/S)
         (PendingDelay
          ,OWNERS-EMPTY
          (Work ,OWNERS-EMPTY ,FAIL-GOAL ,SIGMA/S)))
        ,RIGHT-GOAL)))
    `(Forced
      ,OWNERS-EMPTY
      (More
       (DisjL
        ,OWNERS-EMPTY
        (Work ,OWNERS-EMPTY ,RIGHT-GOAL ,SIGMA/S)
        (Conj
         ,OWNERS-EMPTY
         (PendingDelay
          ,OWNERS-EMPTY
          (Work ,OWNERS-EMPTY ,FAIL-GOAL ,SIGMA/S))
         ,RIGHT-GOAL)))))))

(define ALTERNATING/S
  `(Forced
    ,OWNERS-U0
    (Emit
     ,OWNERS-U1
     (Answer ,OWNERS-U2 ,SIGMA/S)
     (Forced
      ,OWNERS-U2
      (More
       (DisjL
        ,OWNERS-U3
        (PendingDelay
         ,OWNERS-U4
         (Work ,OWNERS-EMPTY ,SUCCEED-GOAL ,SIGMA/S))
        (Dead ,OWNERS-U4)))))))

(define ALTERNATING/E
  `(Forced
    (Emit
     (Answer ,(sigma/e '(u:0 u:1 u:2)))
     (Forced
      (More
       (DisjL
        (PendingDelay
         (Work ,SUCCEED-GOAL ,(sigma/e '(u:0 u:1 u:2 u:3 u:4))))
        (Dead (Support u:0 u:1 u:2 u:3 u:4))))))))

(define ALTERNATING/N
  `(Forced
    (Emit
     (Answer ,(sigma/n 3))
     (Forced
      (More
       (DisjL
        (PendingDelay (Work ,SUCCEED-GOAL ,(sigma/n 5)))
        (Dead 5)))))))

(define SCHEDULER-BARRIER/S
  `(More
    (DisjL
     ,OWNERS-EMPTY
     (PendingDelay
      ,OWNERS-EMPTY
      (Work ,OWNERS-EMPTY ,SUCCEED-GOAL ,SIGMA/S))
     (Dead ,OWNERS-EMPTY))))

(define TRACE-SOURCE/S
  `(More
    (Work
     ,OWNERS-EMPTY
     (suspend
      (,FAIL-GOAL ∨ ,SUCCEED-GOAL (label "trace-choice"))
      (label "trace-delay"))
     ,SIGMA/S)))

(define EXPECTED-TRACE-LABELS
  '(suspend-goal
    force-delay
    expand-disjunction
    fail
    skip-left-failure
    succeed
    finish-success))

(define (rule-names relation)
  (map (lambda (name) (string->symbol (~a name)))
       (reduction-relation->rule-names relation)))

(define (wf-proofs/s frontier)
  (build-derivations (swf:wf-search-oracle/s? ,frontier)))

(define (wf-proofs/e frontier)
  (build-derivations (ewf:wf-search-oracle/e? ,frontier)))

(define (wf-proofs/n frontier)
  (build-derivations (nwf:wf-search-oracle/n? ,frontier)))

(define (trace-final source trace)
  (match trace
    ['() source]
    [_ (second (last trace))]))

(define-runtime-path s-language-path "s/language.rkt")
(define-runtime-path s-source-path "s/source.rkt")
(define-runtime-path s-wf-path "s/wf.rkt")
(define-runtime-path e-language-path "e/language.rkt")
(define-runtime-path e-source-path "e/source.rkt")
(define-runtime-path e-wf-path "e/wf.rkt")
(define-runtime-path n-language-path "n/language.rkt")
(define-runtime-path n-source-path "n/source.rkt")
(define-runtime-path n-wf-path "n/wf.rkt")
(define-runtime-path vertical-path "vertical.rkt")
(define-runtime-path shared-path "private/shared.rkt")

(define SEARCH-ORACLE-TESTS
  (test-suite
   "independent zero-rule Search oracle"

   (test-case
    "joined grammar has both features but no scheduler carrier"
    (define joined-goal
      '(suspend
        ((succeed (label "left"))
         ∨
         (fail (label "right"))
         (label "choice"))
        (label "delay")))
    (check-true (redex-match? sl:search-s-oracle-lang g joined-goal))
    (check-true (redex-match? el:search-e-oracle-lang g joined-goal))
    (check-true (redex-match? nl:search-n-oracle-lang g joined-goal))
    (check-false
     (redex-match?
      sl:search-s-oracle-lang
      W
      '(DisjR (Owners) (Dead (Owners)) (Dead (Owners)))))
    (check-false
     (redex-match?
      el:search-e-oracle-lang
      W
      '(DisjR (Dead (Support)) (PendingDelay (Dead (Support))))))
    (check-false
     (redex-match?
      nl:search-n-oracle-lang
      W
      '(DisjR (Dead 0) (PendingDelay (Dead 0))))))

   (test-case
    "all six compositions have exactly 21 labels and zero Search labels"
    (check-equal? SEARCH-OWNED-RULE-NAMES/SEARCH-ORACLE '())
    (check-equal? (length SEARCH-RULE-NAMES/SEARCH-ORACLE) 21)
    (for ([actual
           (in-list
            (map rule-names
                 (list ss:search-s-oracle-red
                       ss:search-s-oracle-red/disjunction-first
                       es:search-e-oracle-red
                       es:search-e-oracle-red/disjunction-first
                       ns:search-n-oracle-red
                       ns:search-n-oracle-red/disjunction-first)))])
      (check-equal? (length actual) 21)
      (check-equal? (length actual) (length (remove-duplicates actual)))
      (check-equal? (sort actual symbol<?)
                    SEARCH-RULE-NAMES/SEARCH-ORACLE)))

   (test-case
    "eight mixed inherited equations preserve exact raw proofs"
    (for ([case (in-list MIXED-CASES/S)])
      (define case-name (~a (mixed-case-name case)))
      (define label (mixed-case-label case))
      (define source/s (mixed-case-source case))
      (define target/s (mixed-case-target case))
      (define source/e (Q-SE/F/search source/s))
      (define target/e (Q-SE/F/search target/s))
      (define source/n (Q-SN/F/search source/s))
      (define target/n (Q-SN/F/search target/s))
      (define expected/s (list (list label target/s)))
      (define expected/e (list (list label target/e)))
      (define expected/n (list (list label target/n)))

      (check-equal? (ss:raw-successors/search/s source/s)
                    expected/s
                    case-name)
      (check-equal?
       (ss:raw-successors/search/s/disjunction-first source/s)
       expected/s
       case-name)
      (check-equal? (es:raw-successors/search/e source/e)
                    expected/e
                    case-name)
      (check-equal?
       (es:raw-successors/search/e/disjunction-first source/e)
       expected/e
       case-name)
      (check-equal? (ns:raw-successors/search/n source/n)
                    expected/n
                    case-name)
      (check-equal?
       (ns:raw-successors/search/n/disjunction-first source/n)
       expected/n
       case-name)

      ;; Exact proof counts guard both reduction and WF multiplicity.
      (for ([proofs
             (in-list
              (list (wf-proofs/s source/s)
                    (wf-proofs/s target/s)
                    (wf-proofs/e source/e)
                    (wf-proofs/e target/e)
                    (wf-proofs/n source/n)
                    (wf-proofs/n target/n)))])
        (check-equal? (length proofs) 1 case-name))

      (check-true (Q-SE-step-square/raw?/search source/s))
      (check-true (Q-EN-step-square/raw?/search source/e))
      (check-true (Q-SN-step-square/raw?/search source/s))
      (check-true (Q-SN-composition?/search source/s))
      (for ([sides
             (in-list
              (list (Q-SE-step-square-sides/search source/s)
                    (Q-EN-step-square-sides/search source/e)
                    (Q-SN-step-square-sides/search source/s)))])
        (check-equal? (map length sides) '(1 1)))))

   (test-case
    "alternating wrappers preserve state copies and sibling-local reuse"
    (check-equal? (Q-SE/F/search ALTERNATING/S) ALTERNATING/E)
    (check-equal? (Q-EN/F/search ALTERNATING/E) ALTERNATING/N)
    (check-equal? (Q-SN/F/search ALTERNATING/S) ALTERNATING/N)
    (check-true (Q-SN-composition?/search ALTERNATING/S))
    (check-equal? (S-world-support/search ALTERNATING/S)
                  '(u:0 u:1 u:2 u:3 u:4))
    (check-equal? (E-live-support/search ALTERNATING/E)
                  '(u:0 u:1 u:2 u:3 u:4))
    (check-equal? (length (wf-proofs/s ALTERNATING/S)) 1)
    (check-equal? (length (wf-proofs/e ALTERNATING/E)) 1)
    (check-equal? (length (wf-proofs/n ALTERNATING/N)) 1)
    ;; u:2 is independently reusable by Emit's answer and residual; u:4 is
    ;; independently reusable by the two DisjL siblings.  N records 3 and 5,
    ;; never a fused whole-frontier counter.
    (check-equal? ALTERNATING/N
                  `(Forced
                    (Emit
                     (Answer ,(sigma/n 3))
                     (Forced
                      (More
                       (DisjL
                        (PendingDelay
                         (Work ,SUCCEED-GOAL ,(sigma/n 5)))
                        (Dead 5))))))))

   (test-case
    "delayed active choice is a WF zero-successor scheduler barrier"
    (define barrier/e (Q-SE/F/search SCHEDULER-BARRIER/S))
    (define barrier/n (Q-SN/F/search SCHEDULER-BARRIER/S))
    (for ([successors
           (in-list
            (list (ss:raw-successors/search/s SCHEDULER-BARRIER/S)
                  (ss:raw-successors/search/s/disjunction-first
                   SCHEDULER-BARRIER/S)
                  (es:raw-successors/search/e barrier/e)
                  (es:raw-successors/search/e/disjunction-first barrier/e)
                  (ns:raw-successors/search/n barrier/n)
                  (ns:raw-successors/search/n/disjunction-first barrier/n)))])
      (check-equal? successors '()))
    (check-equal? (length (wf-proofs/s SCHEDULER-BARRIER/S)) 1)
    (check-equal? (length (wf-proofs/e barrier/e)) 1)
    (check-equal? (length (wf-proofs/n barrier/n)) 1)
    (check-true (Q-SE-step-square/raw?/search SCHEDULER-BARRIER/S))
    (check-true (Q-EN-step-square/raw?/search barrier/e))
    (check-true (Q-SN-step-square/raw?/search SCHEDULER-BARRIER/S)))

   (test-case
    "lexical substitution crosses alternating goal features with shadowing"
    (define source-goal
      '(∃ (x:outer)
          (suspend
           ((x:outer =? x:free (label "left"))
            ∨
            (suspend
             (x:free != x:outer (label "right"))
             (label "inner-delay"))
            (label "choice"))
           (label "outer-delay"))
          (label "shadow")))
    (define expected-symbolic
      '(∃ (x:outer)
          (suspend
           ((x:outer =? u:8 (label "left"))
            ∨
            (suspend
             (u:8 != x:outer (label "right"))
             (label "inner-delay"))
            (label "choice"))
           (label "outer-delay"))
          (label "shadow")))
    (define expected-numeric
      '(∃ (x:outer)
          (suspend
           ((x:outer =? 8 (label "left"))
            ∨
            (suspend
             (8 != x:outer (label "right"))
             (label "inner-delay"))
            (label "choice"))
           (label "outer-delay"))
          (label "shadow")))
    (check-equal?
     (ss:subst-goal/search/s
      source-goal
      '((x:outer u:7) (x:free u:8)))
     expected-symbolic)
    (check-equal?
     (es:subst-goal/search/e
      source-goal
      '((x:outer u:7) (x:free u:8)))
     expected-symbolic)
    (check-equal?
     (term
      (ns:subst-goal/search/n
       ,source-goal
       ((x:outer 7) (x:free 8))))
     expected-numeric))

   (test-case
    "one bounded mixed trace agrees in S E and N without a scheduler turn"
    (define source/e (Q-SE/F/search TRACE-SOURCE/S))
    (define source/n (Q-SN/F/search TRACE-SOURCE/S))
    (define trace/s (ss:trace/search/s TRACE-SOURCE/S 12))
    (define trace/e (es:trace/search/e source/e 12))
    (define trace/n (ns:trace/search/n source/n 12))
    (check-equal? (map first trace/s) EXPECTED-TRACE-LABELS)
    (check-equal? (map first trace/e) EXPECTED-TRACE-LABELS)
    (check-equal? (map first trace/n) EXPECTED-TRACE-LABELS)
    (check-equal? (length trace/s) 7)
    (check-equal? (length trace/e) 7)
    (check-equal? (length trace/n) 7)
    (check-equal? (Q-SE/F/search (trace-final TRACE-SOURCE/S trace/s))
                  (trace-final source/e trace/e))
    (check-equal? (Q-SN/F/search (trace-final TRACE-SOURCE/S trace/s))
                  (trace-final source/n trace/n)))

   (test-case
    "oracle modules import no framework generated or production layer"
    (for ([path
           (in-list
            (list s-language-path
                  s-source-path
                  s-wf-path
                  e-language-path
                  e-source-path
                  e-wf-path
                  n-language-path
                  n-source-path
                  n-wf-path
                  vertical-path
                  shared-path))])
      (define contents (file->string path))
      (check-false (regexp-match? #rx"framework/" contents))
      (check-false (regexp-match? #rx"generated/" contents))
      (check-false (regexp-match? #rx"src/search-lattice" contents))
      (check-false (regexp-match? #rx"reduction-relations/" contents))))))

(module+ test
  (run-tests SEARCH-ORACLE-TESTS))

(module+ main
  (define failures (run-tests SEARCH-ORACLE-TESTS))
  (unless (zero? failures)
    (error 'search-oracle-tests "~a test failure(s)" failures)))
